---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/cf-openstack-validator-ci
    tag: 'latest'

inputs:
- name: validator-src
- name: openstack-cpi-src
- name: bosh-cli
- name: terraform-validator

params:
  AUTH_URL:           ""
  USERNAME:           ""
  API_KEY:            ""
  DOMAIN:             ""
  PROJECT:            ""
  PROJECT_ID:         ""
  DEFAULT_KEY_NAME:   ""
  NETWORK_ID:         ""
  FLOATING_IP:        ""
  STATIC_IP:          ""
  PUBLIC_IMAGE_ID:    ""
  PRIVATE_KEY:        ""
  INSTANCE_TYPE:      ""
  NTP_SERVER:         ""
  CA_CERT:            ""
  AVAILABILITY_ZONE:  ""
  OBJECT_STORAGE:     ""
  PIPELINE_NAME:      ""
  MTU_SIZE:           ""
  AUTO_ANTI_AFFINITY: ""

run:
  path: validator-src/ci/cpi-openstack-compatibility/tasks/validate.sh
